version: '2.2'
services:
   mysql:
      build: ./mysql
#      image: mysql:5.6
      ports:
        - '3307:3306'
      volumes:
        - '/opt/majordomo/data:/var/lib/mysql'
      environment:
        MYSQL_ROOT_PASSWORD: forrest
        MYSQL_HOST: mysql
        MYSQL_USER: majordomo
        MYSQL_PASSWORD: majordomo
        MYSQL_DATABASE: db_terminal

   majordomo:
      build: 
        context: ./docker
      ports:
        - '8090:80'
        - '9001:9001'
        - '8002:8002'
      
      volumes:
         - '/opt/majordomo/logs:/var/logs/www'
#         - '/opt/majordomo/www:/var/www'

      environment:
        MYSQL_HOST: 192.168.1.50
        MYSQL_PORT: 3307
        MYSQL_USER: majordomo
        MYSQL_PASSWORD: majordomo
        MYSQL_DATABASE: db_terminal
        MJDM_TITLE: "Tall's MajorDoMo"
        MJDM_BASE_URL: "http://192.168.1.50:8090"

      links:
        - mysql

#      network_mode: "host"

